import prisma from "@root/prisma.js";
import dayjs from "dayjs";
import utc from "dayjs/plugin/utc.js";
import timezone from "dayjs/plugin/timezone.js";
import jwt from "jsonwebtoken";
import { hashPassword, comparePassword } from "@/utils/auth.js";
import { ApiError } from "@/utils/ApiError.js";
import STATUS_CODES from "@/utils/statusCodes.js";
import { generateOtp, getOtpExpiry } from "@/utils/otp.js";
import { sendOtpEmail } from "@/utils/email.js";
import {
  RegisterBody,
  LoginBody,
  VerifyEmailOtpBody,
  ForgotPasswordBody,
  ResetPasswordBody,
  RegisterResponse,
  userSelectFields,
} from "./auth.types.js";

dayjs.extend(utc);
dayjs.extend(timezone);

const formatUser = (user: any) => ({
  ...user,
  createdAt: dayjs
    .utc(user.createdAt)
    .tz(user.timezone)
    .format("YYYY-MM-DDTHH:mm"),
  updatedAt: dayjs
    .utc(user.updatedAt)
    .tz(user.timezone)
    .format("YYYY-MM-DDTHH:mm"),
});

const getHighestRole = (
  roleNames: string[],
): "USER" | "ADMIN" | "SUPERADMIN" => {
  if (roleNames.includes("SUPERADMIN") || roleNames.includes("SUPER_ADMIN"))
    return "SUPERADMIN";
  if (roleNames.includes("ADMIN")) return "ADMIN";
  return "USER";
};

class AuthService {
  private normalizeEmail(email: string) {
    return email.trim().toLowerCase();
  }

  private createToken(user: { id: number; role?: string; timezone?: string; userRoles?: Array<{ role: { name: string } }> }) {
    if (!process.env.JWT_SECRET) {
      throw new ApiError(
        "JWT secret is not defined",
        STATUS_CODES.SERVER_ERROR,
      );
    }

    const roleNames = user.userRoles?.map((ur) => ur.role.name) ?? [];
    const highestRole = getHighestRole(roleNames);

    return jwt.sign(
      {
        id: user.id,
        role: highestRole,
        timezone: user.timezone ?? "UTC",
      },
      process.env.JWT_SECRET,
      { expiresIn: "90d" },
    );
  }

  private getArchivedEmail(email: string, userId: number) {
    return `${email}__deleted_${userId}_${Date.now()}`;
  }

  async register(data: RegisterBody): Promise<RegisterResponse> {
    const email = this.normalizeEmail(data.email);
    const existingUser = await prisma.user.findFirst({
      where: { email },
    });

    if (existingUser && !existingUser.isDeleted) {
      throw new ApiError("Email already registered", STATUS_CODES.CONFLICT);
    }

    if (existingUser && existingUser.isDeleted) {
      await prisma.user.update({
        where: { id: existingUser.id },
        data: {
          email: this.getArchivedEmail(existingUser.email, existingUser.id),
          isActive: false,
        },
      });
    }

    const hashedPassword = await hashPassword(data.password);
    const otp = generateOtp();
    const otpHash = await hashPassword(otp);
    const otpExpiresAt = getOtpExpiry();

    const roleRecord = await prisma.role.findUnique({
      where: { name: "USER" },
    });
    if (!roleRecord)
      throw new ApiError("USER role not found", STATUS_CODES.SERVER_ERROR);

    // Find Free plan for auto-assignment
    const freePlan = await prisma.plan.findFirst({ where: { name: "Free" } });

    const user = await prisma.$transaction(async (tx) => {
      const createdUser = await tx.user.create({
        data: {
          firstName: data.firstName,
          lastName: data.lastName,
          email,
          password: hashedPassword,
          emailVerificationOtpHash: otpHash,
          emailVerificationOtpExpiresAt: otpExpiresAt,
        },
        select: userSelectFields,
      });

      await tx.userRole.create({
        data: {
          userId: createdUser.id,
          roleId: roleRecord.id,
        },
      });

      // Auto-assign Free plan subscription + wallet
      if (freePlan) {
        const now = new Date();
        const periodEnd = dayjs(now).add(1, "month").toDate();

        await tx.subscription.create({
          data: {
            userId: createdUser.id,
            planId: freePlan.id,
            status: "ACTIVE",
            billingCycle: "MONTHLY",
            startedAt: now,
            expiresAt: periodEnd,
            autoRenew: true,
          },
        });

        await tx.userWallet.create({
          data: {
            userId: createdUser.id,
            tokensRemaining: freePlan.tokenLimit,
            tokensUsed: 0,
            currentPeriodStart: now,
            currentPeriodEnd: periodEnd,
          },
        });

        await tx.userPreference.create({
          data: {
            userId: createdUser.id,
            enableFollowUpQuestions: true,
          },
        });

        await tx.contextMemory.create({
          data: {
            userId: createdUser.id,
            type: "GLOBAL",
            title: "My Name",
            memory: `My name is ${data.firstName} ${data.lastName}`,
            isAutoSelected: true,
            isAutoGenerated: true,
          },
        });
      }

      const user = await tx.user.findUnique({
        where: { id: createdUser.id },
        select: userSelectFields,
      });

      await sendOtpEmail(email, otp, "EMAIL_VERIFICATION");

      return user;
    });

    if (!user) {
      throw new ApiError("Failed to create user session", STATUS_CODES.SERVER_ERROR);
    }

    const token = this.createToken(user as any);

    return {
      user: formatUser(user),
      token,
      requiresEmailVerification: true,
    };
  }

  async login(data: LoginBody) {
    const email = this.normalizeEmail(data.email);
    const user = await prisma.user.findFirst({
      where: { email, isDeleted: false },
      include: {
        userRoles: {
          include: { role: true },
        },
      },
    });

    if (!user) {
      throw new ApiError(
        "Invalid email or password",
        STATUS_CODES.UNAUTHORIZED,
      );
    }

    const hasUserRole = user.userRoles.some((ur) => ur.role.name === "USER");
    if (!hasUserRole) {
      throw new ApiError(
        "Access denied. You do not have user privileges",
        STATUS_CODES.FORBIDDEN,
      );
    }

    const isPasswordValid = await comparePassword(data.password, user.password);
    if (!isPasswordValid) {
      throw new ApiError(
        "Invalid email or password",
        STATUS_CODES.UNAUTHORIZED,
      );
    }

    if (!user.isVerified) {
      const otp = generateOtp();
      const otpHash = await hashPassword(otp);
      const otpExpiresAt = getOtpExpiry();

      await prisma.user.update({
        where: { id: user.id },
        data: {
          emailVerificationOtpHash: otpHash,
          emailVerificationOtpExpiresAt: otpExpiresAt,
        },
      });

      await sendOtpEmail(email, otp, "EMAIL_VERIFICATION");

      return {
        requiresEmailVerification: true,
        email,
      };
    }

    const token = this.createToken(user);

    const {
      password: _password,
      emailVerificationOtpHash: _emailVerificationOtpHash,
      emailVerificationOtpExpiresAt: _emailVerificationOtpExpiresAt,
      passwordResetOtpHash: _passwordResetOtpHash,
      passwordResetOtpExpiresAt: _passwordResetOtpExpiresAt,
      ...userWithoutPassword
    } = user;

    return { user: formatUser(userWithoutPassword), token };
  }

  async verifyEmailOtp(data: VerifyEmailOtpBody) {
    const email = this.normalizeEmail(data.email);
    const user = await prisma.user.findFirst({
      where: { email, isDeleted: false },
    });

    if (!user) {
      throw new ApiError("User not found", STATUS_CODES.NOT_FOUND);
    }

    if (user.isVerified) {
      return { verified: true };
    }

    if (
      !user.emailVerificationOtpHash ||
      !user.emailVerificationOtpExpiresAt ||
      user.emailVerificationOtpExpiresAt.getTime() < Date.now()
    ) {
      throw new ApiError(
        "OTP expired. Please request a new OTP",
        STATUS_CODES.BAD_REQUEST,
      );
    }

    const isOtpValid = await comparePassword(
      data.otp,
      user.emailVerificationOtpHash,
    );

    if (!isOtpValid) {
      throw new ApiError("Invalid OTP", STATUS_CODES.BAD_REQUEST);
    }

    await prisma.user.update({
      where: { id: user.id },
      data: {
        isVerified: true,
        emailVerificationOtpHash: null,
        emailVerificationOtpExpiresAt: null,
      },
    });

    return { verified: true };
  }

  async resendEmailVerificationOtp(data: ForgotPasswordBody) {
    const email = this.normalizeEmail(data.email);
    const user = await prisma.user.findFirst({
      where: { email, isDeleted: false },
    });

    if (!user) {
      throw new ApiError("User not found", STATUS_CODES.NOT_FOUND);
    }

    if (user.isVerified) {
      throw new ApiError("Email is already verified", STATUS_CODES.BAD_REQUEST);
    }

    const otp = generateOtp();
    const otpHash = await hashPassword(otp);
    const otpExpiresAt = getOtpExpiry();

    await prisma.user.update({
      where: { id: user.id },
      data: {
        emailVerificationOtpHash: otpHash,
        emailVerificationOtpExpiresAt: otpExpiresAt,
      },
    });

    await sendOtpEmail(email, otp, "EMAIL_VERIFICATION");

    return { sent: true };
  }

  async forgotPassword(data: ForgotPasswordBody) {
    const email = this.normalizeEmail(data.email);
    const user = await prisma.user.findFirst({
      where: { email, isDeleted: false },
    });

    if (user) {
      const otp = generateOtp();
      const otpHash = await hashPassword(otp);
      const otpExpiresAt = getOtpExpiry();

      await prisma.user.update({
        where: { id: user.id },
        data: {
          passwordResetOtpHash: otpHash,
          passwordResetOtpExpiresAt: otpExpiresAt,
        },
      });

      await sendOtpEmail(email, otp, "PASSWORD_RESET");
    }

    return { sent: true };
  }

  async resetPassword(data: ResetPasswordBody) {
    const email = this.normalizeEmail(data.email);
    const user = await prisma.user.findFirst({
      where: { email, isDeleted: false },
    });

    if (!user) {
      throw new ApiError("User not found", STATUS_CODES.NOT_FOUND);
    }

    if (
      !user.passwordResetOtpHash ||
      !user.passwordResetOtpExpiresAt ||
      user.passwordResetOtpExpiresAt.getTime() < Date.now()
    ) {
      throw new ApiError(
        "OTP expired. Please request a new OTP",
        STATUS_CODES.BAD_REQUEST,
      );
    }

    const isOtpValid = await comparePassword(
      data.otp,
      user.passwordResetOtpHash,
    );
    if (!isOtpValid) {
      throw new ApiError("Invalid OTP", STATUS_CODES.BAD_REQUEST);
    }

    const nextPasswordHash = await hashPassword(data.newPassword);
    await prisma.user.update({
      where: { id: user.id },
      data: {
        password: nextPasswordHash,
        passwordResetOtpHash: null,
        passwordResetOtpExpiresAt: null,
      },
    });

    return { updated: true };
  }
}

export default AuthService;
