import prisma from "@root/prisma.js";
import { ApiError } from "@/utils/ApiError.js";
import STATUS_CODES from "@/utils/statusCodes.js";
import { CreateContextBody, UpdateContextBody } from "./context.types.js";
import {
  getPaginationOptions,
  formatPaginationResponse,
} from "@/utils/paginationUtils.js";
import { buildPrismaQuery } from "prisma-qb";

class ContextService {
  async create(userId: number, data: CreateContextBody) {
    if (data.type === "GLOBAL") {
      const globalCount = await prisma.contextMemory.count({
        where: { userId, type: "GLOBAL", isDeleted: false },
      });
      if (globalCount >= 20) {
        throw new ApiError(
          "Maximum of 20 active global contexts allowed per user",
          STATUS_CODES.BAD_REQUEST,
        );
      }
      data.isAutoSelected = true;
    } else if (data.type === "FOLDER" && data.folderId) {
      const folderCount = await prisma.contextMemory.count({
        where: {
          userId,
          type: "FOLDER",
          folderId: data.folderId,
          isDeleted: false,
        },
      });
      if (folderCount >= 10) {
        throw new ApiError(
          "Maximum of 10 active contexts allowed per folder",
          STATUS_CODES.BAD_REQUEST,
        );
      }

      const folder = await prisma.folder.findFirst({
        where: { id: data.folderId, userId, isDeleted: false },
      });
      if (!folder) {
        throw new ApiError("Folder not found", STATUS_CODES.NOT_FOUND);
      }
    } else if (data.type !== "CUSTOM") {
      data.type = "CUSTOM"; // Fallback
    }

    const context = await prisma.contextMemory.create({
      data: {
        ...data,
        userId,
      },
    });

    return context;
  }

  async list(userId: number, query: any) {
    const { take, skip, page, pageSize } = getPaginationOptions(query, 20);

    const { where: qbWhere, orderBy } = buildPrismaQuery({
      query,
      searchFields: [{ field: "title" }, { field: "memory" }],
      filterFields: [
        { key: "type", field: "type", type: "string" },
        { key: "isAutoSelected", field: "isAutoSelected", type: "boolean" },
        { key: "folderId", field: "folderId", type: "number" },
        { key: "origin", field: "origin", type: "string" },
      ],
      sortFields: [
        { key: "createdAt", field: "createdAt" },
        { key: "priority", field: "priority" },
        { key: "title", field: "title" },
      ],
      defaultSort: { key: "createdAt", order: "desc" },
      softDelete: { field: "isDeleted", value: false },
      allowedQueryKeys: [
        "page",
        "pageSize",
        "type",
        "isAutoSelected",
        "folderId",
        "origin",
      ],
    });

    const where = { ...qbWhere, userId };

    const [contexts, totalRecords] = await Promise.all([
      prisma.contextMemory.findMany({
        where,
        skip,
        take,
        orderBy,
      }),
      prisma.contextMemory.count({ where }),
    ]);

    return formatPaginationResponse(contexts, totalRecords, page, pageSize);
  }

  async getById(userId: number, contextId: number) {
    const context = await prisma.contextMemory.findFirst({
      where: { id: contextId, userId, isDeleted: false },
    });

    if (!context) {
      throw new ApiError("Context not found", STATUS_CODES.NOT_FOUND);
    }

    return context;
  }

  async update(userId: number, contextId: number, data: UpdateContextBody) {
    const context = await prisma.contextMemory.findFirst({
      where: { id: contextId, userId, isDeleted: false },
    });

    if (!context) {
      throw new ApiError("Context not found", STATUS_CODES.NOT_FOUND);
    }

    if (context.isAutoGenerated) {
      throw new ApiError(
        "This is system generated context, cannot be edited",
        STATUS_CODES.BAD_REQUEST,
      );
    }

    if (data.folderId) {
      const folder = await prisma.folder.findFirst({
        where: { id: data.folderId, userId, isDeleted: false },
      });
      if (!folder) {
        throw new ApiError("Folder not found", STATUS_CODES.NOT_FOUND);
      }
    }

    const updatedContext = await prisma.contextMemory.update({
      where: { id: contextId },
      data: {
        ...data,
        // Once a user edits an auto-distilled memory, it's no longer just
        // the model's guess — promote it to USER-owned so the distillation
        // worker's cap-eviction logic (which only culls DISTILLED rows)
        // never deletes something the user has curated.
        ...(context.origin === "DISTILLED" ? { origin: "USER" as const } : {}),
      },
    });

    return updatedContext;
  }

  async delete(userId: number, contextId: number) {
    const context = await prisma.contextMemory.findFirst({
      where: { id: contextId, userId, isDeleted: false },
    });

    if (!context) {
      throw new ApiError("Context not found", STATUS_CODES.NOT_FOUND);
    }

    if (context.isAutoGenerated) {
      throw new ApiError(
        "This is system generated context, cannot be deleted",
        STATUS_CODES.BAD_REQUEST,
      );
    }

    await prisma.contextMemory.update({
      where: { id: contextId },
      data: { isDeleted: true, deletedAt: new Date() },
    });

    return { message: "Context deleted successfully" };
  }

  async getForSidebar(userId: number, query: any) {
    const folderId =
      query.folderId !== undefined && query.folderId !== null
        ? Number(query.folderId)
        : null;
    const search = String(query.search || "").trim();

    const where: any = {
      userId,
      isDeleted: false,
      ...(search
        ? {
            OR: [
              { title: { contains: search, mode: "insensitive" } },
              { memory: { contains: search, mode: "insensitive" } },
            ],
          }
        : {}),
    };

    const allContexts = await prisma.contextMemory.findMany({
      where,
      orderBy: [{ priority: "desc" }, { createdAt: "desc" }],
    });

    return {
      globalContexts: allContexts.filter((ctx) => ctx.type === "GLOBAL"),
      folderContexts: allContexts.filter(
        (ctx) =>
          ctx.type === "FOLDER" &&
          (folderId ? ctx.folderId === folderId : true),
      ),
      customContexts: allContexts.filter((ctx) => ctx.type === "CUSTOM"),
    };
  }
}

export default ContextService;
