import prisma from "@root/prisma.js";
import { ApiError } from "@/utils/ApiError.js";
import STATUS_CODES from "@/utils/statusCodes.js";
import { CreateContextBody, UpdateContextBody } from "./context.types.js";
import {
  getPaginationOptions,
  formatPaginationResponse,
} from "@/utils/paginationUtils.js";
import { buildPrismaQuery } from "prisma-qb";

class ContextService {
  async create(userId: number, data: CreateContextBody) {
    if (data.type === "GLOBAL") {
      const globalCount = await prisma.contextMemory.count({
        where: { userId, type: "GLOBAL", isDeleted: false },
      });
      if (globalCount >= 20) {
        throw new ApiError(
          "Maximum of 20 active global contexts allowed per user",
          STATUS_CODES.BAD_REQUEST,
        );
      }
      data.isAutoSelected = true;
    } else if (data.type === "FOLDER" && data.folderId) {
      const folderCount = await prisma.contextMemory.count({
        where: {
          userId,
          type: "FOLDER",
          folderId: data.folderId,
          isDeleted: false,
        },
      });
      if (folderCount >= 10) {
        throw new ApiError(
          "Maximum of 10 active contexts allowed per folder",
          STATUS_CODES.BAD_REQUEST,
        );
      }

      const folder = await prisma.folder.findFirst({
        where: { id: data.folderId, userId, isDeleted: false },
      });
      if (!folder) {
        throw new ApiError("Folder not found", STATUS_CODES.NOT_FOUND);
      }
    } else if (data.type !== "CUSTOM") {
      data.type = "CUSTOM"; // Fallback
    }

    const context = await prisma.contextMemory.create({
      data: {
        ...data,
        userId,
      },
    });

    return context;
  }

  async list(userId: number, query: any) {
    const { take, skip, page, pageSize } = getPaginationOptions(query, 20);

    const { where: qbWhere, orderBy } = buildPrismaQuery({
      query,
      searchFields: [{ field: "title" }, { field: "memory" }],
      filterFields: [
        { key: "type", field: "type", type: "string" },
        { key: "isAutoSelected", field: "isAutoSelected", type: "boolean" },
        { key: "folderId", field: "folderId", type: "number" },
      ],
      sortFields: [
        { key: "createdAt", field: "createdAt" },
        { key: "priority", field: "priority" },
        { key: "title", field: "title" },
      ],
      defaultSort: { key: "createdAt", order: "desc" },
      softDelete: { field: "isDeleted", value: false },
      allowedQueryKeys: [
        "page",
        "pageSize",
        "type",
        "isAutoSelected",
        "folderId",
      ],
    });

    const where = { ...qbWhere, userId };

    const [contexts, totalRecords] = await Promise.all([
      prisma.contextMemory.findMany({
        where,
        skip,
        take,
        orderBy,
      }),
      prisma.contextMemory.count({ where }),
    ]);

    return formatPaginationResponse(contexts, totalRecords, page, pageSize);
  }

  async getById(userId: number, contextId: number) {
    const context = await prisma.contextMemory.findFirst({
      where: { id: contextId, userId, isDeleted: false },
    });

    if (!context) {
      throw new ApiError("Context not found", STATUS_CODES.NOT_FOUND);
    }

    return context;
  }

  async update(userId: number, contextId: number, data: UpdateContextBody) {
    const context = await prisma.contextMemory.findFirst({
      where: { id: contextId, userId, isDeleted: false },
    });

    if (!context) {
      throw new ApiError("Context not found", STATUS_CODES.NOT_FOUND);
    }

    if (data.folderId) {
      const folder = await prisma.folder.findFirst({
        where: { id: data.folderId, userId, isDeleted: false },
      });
      if (!folder) {
        throw new ApiError("Folder not found", STATUS_CODES.NOT_FOUND);
      }
    }

    const updatedContext = await prisma.contextMemory.update({
      where: { id: contextId },
      data: {
        ...data,
      },
    });

    return updatedContext;
  }

  async delete(userId: number, contextId: number) {
    const context = await prisma.contextMemory.findFirst({
      where: { id: contextId, userId, isDeleted: false },
    });

    if (!context) {
      throw new ApiError("Context not found", STATUS_CODES.NOT_FOUND);
    }

    if (context.isAutoGenerated) {
      throw new ApiError(
        "This is system generated context, cannot be deleted",
        STATUS_CODES.BAD_REQUEST,
      );
    }

    await prisma.contextMemory.update({
      where: { id: contextId },
      data: { isDeleted: true, deletedAt: new Date() },
    });

    return { message: "Context deleted successfully" };
  }

  async getForSidebar(userId: number, query: any) {
    // 1. auto selected items as whole
    const autoSelected = await prisma.contextMemory.findMany({
      where: {
        userId,
        isAutoSelected: true,
        isDeleted: false,
      },
      orderBy: [{ priority: "desc" }, { createdAt: "desc" }],
    });

    // 2. other items in pagination
    const { take, skip, page, pageSize } = getPaginationOptions(query, 20);

    const { where: qbWhere, orderBy } = buildPrismaQuery({
      query,
      searchFields: [{ field: "title" }, { field: "memory" }],
      filterFields: [
        { key: "type", field: "type", type: "string" },
        { key: "folderId", field: "folderId", type: "number" },
      ],
      sortFields: [
        { key: "createdAt", field: "createdAt" },
        { key: "priority", field: "priority" },
        { key: "title", field: "title" },
      ],
      defaultSort: { key: "createdAt", order: "desc" },
      softDelete: { field: "isDeleted", value: false },
      allowedQueryKeys: ["page", "pageSize", "type", "folderId"],
    });

    // Enforce getting items that are NOT auto-selected
    const where = { ...qbWhere, userId, isAutoSelected: false };

    const [otherContexts, totalRecords] = await Promise.all([
      prisma.contextMemory.findMany({
        where,
        skip,
        take,
        orderBy,
      }),
      prisma.contextMemory.count({ where }),
    ]);

    const paginatedOthers = formatPaginationResponse(
      otherContexts,
      totalRecords,
      page,
      pageSize,
    );

    return {
      autoSelected,
      others: paginatedOthers,
    };
  }
}

export default ContextService;
