"use client";

import Link from "next/link";
import Image from "next/image";
import { ArrowLeft } from "lucide-react";

const LAST_UPDATED = "July 22, 2026";

const SECTIONS: { title: string; body: React.ReactNode }[] = [
  {
    title: "1. Acceptance of Terms",
    body: (
      <p>
        By creating an account or using AI Colab (the &quot;Service&quot;), you agree to be
        bound by these Terms of Use (&quot;Terms&quot;). If you do not agree to these Terms,
        do not use the Service. We may update these Terms from time to time; continued
        use of the Service after changes take effect constitutes acceptance of the
        revised Terms.
      </p>
    ),
  },
  {
    title: "2. Description of Service",
    body: (
      <p>
        AI Colab is a multi-model AI chat platform that lets you send prompts to one or
        more third-party large language model (LLM) providers through a single
        interface, compare responses, and manage conversations, projects, and
        assistants.
      </p>
    ),
  },
  {
    title: "3. Accounts & Eligibility",
    body: (
      <ul className="list-disc pl-5 space-y-2">
        <li>You must provide accurate information when creating an account and keep your credentials secure.</li>
        <li>You are responsible for all activity that occurs under your account.</li>
        <li>You must be legally permitted to enter into a binding contract in your jurisdiction to use the Service.</li>
      </ul>
    ),
  },
  {
    title: "4. Acceptable Use",
    body: (
      <>
        <p>You agree not to use the Service to:</p>
        <ul className="list-disc pl-5 space-y-2 mt-2">
          <li>Generate content that is illegal, harmful, harassing, or infringes on the rights of others.</li>
          <li>Attempt to bypass usage limits, rate limits, or security controls.</li>
          <li>Reverse-engineer, scrape, or resell access to the Service or the underlying model providers without authorization.</li>
          <li>Use the Service to build a directly competing product without our written consent.</li>
        </ul>
      </>
    ),
  },
  {
    title: "5. Subscriptions, Tokens & Billing",
    body: (
      <>
        <p>
          Access to models is metered using a token-based system. Your plan includes a
          token allowance that resets on your billing cycle; usage beyond your
          allowance may require a paid plan or additional tokens, depending on your
          subscription.
        </p>
        <p className="mt-3">
          <strong className="text-foreground">Token multiplier for premium models.</strong>{" "}
          Not all models cost the same to run. Higher-capability or higher-cost models
          are billed against your token balance using a per-model multiplier applied to
          the tokens actually consumed, so that using a more expensive model draws down
          your balance faster than using a lower-cost one for the same amount of text.
          Free-tier models, where offered, are billed at no cost against your token
          balance. The multiplier (or lack of one) for each model is a fixed,
          disclosed property of that model and is not changed per-request or hidden
          from you — this section exists so that difference in consumption rate is
          never a surprise. Current per-model rates may be shown in the model selector
          or your usage dashboard.
        </p>
        <p className="mt-3">
          Subscription fees, where applicable, are billed in advance and are
          non-refundable except as required by law or as otherwise stated at the time
          of purchase.
        </p>
      </>
    ),
  },
  {
    title: "6. Third-Party AI Providers",
    body: (
      <p>
        The Service routes your prompts to third-party AI model providers to generate
        responses. We do not control, and are not responsible for, the accuracy,
        availability, or content of outputs generated by those providers. Model
        responses may be inaccurate, incomplete, or inappropriate for your use case —
        you are responsible for independently verifying any output before relying on
        it, especially for medical, legal, financial, or safety-critical decisions.
      </p>
    ),
  },
  {
    title: "7. Your Content",
    body: (
      <p>
        You retain ownership of the prompts and files you submit. By submitting
        content to the Service, you grant us a limited license to process, store, and
        transmit that content solely to operate and improve the Service, including
        sending it to the model providers you select. You are responsible for ensuring
        you have the right to submit any content you upload.
      </p>
    ),
  },
  {
    title: "8. Intellectual Property",
    body: (
      <p>
        The Service, including its interface, branding, and underlying software, is
        owned by AI Colab and its licensors and is protected by applicable
        intellectual property laws. These Terms do not grant you any rights to our
        trademarks or branding.
      </p>
    ),
  },
  {
    title: "9. Termination",
    body: (
      <p>
        We may suspend or terminate your access to the Service if you violate these
        Terms or misuse the Service. You may stop using the Service and close your
        account at any time. Provisions that by their nature should survive
        termination (e.g. billing obligations already incurred, limitation of
        liability) will survive.
      </p>
    ),
  },
  {
    title: "10. Disclaimers & Limitation of Liability",
    body: (
      <p>
        The Service is provided &quot;as is&quot; and &quot;as available&quot; without
        warranties of any kind, express or implied. To the maximum extent permitted by
        law, AI Colab will not be liable for any indirect, incidental, special, or
        consequential damages, or for any loss of data, profits, or goodwill arising
        from your use of the Service or reliance on any AI-generated output.
      </p>
    ),
  },
  {
    title: "11. Changes to These Terms",
    body: (
      <p>
        We may revise these Terms from time to time. Material changes will be reflected
        by updating the &quot;Last updated&quot; date below. Your continued use of the
        Service after a revision takes effect constitutes your acceptance of the
        updated Terms.
      </p>
    ),
  },
  {
    title: "12. Contact",
    body: (
      <p>
        Questions about these Terms can be sent to{" "}
        <a
          href="mailto:support@colabplatforms.com"
          className="text-primary underline underline-offset-4"
        >
          support@colabplatforms.com
        </a>
        .
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-dvh bg-background text-foreground">
      <header className="border-b border-border/60">
        <div className="max-w-3xl mx-auto px-5 sm:px-8 py-5 flex items-center justify-between">
          <Link href="/" className="inline-flex items-center gap-2">
            <Image src="/black.webp" alt="AI Colab" width={70} height={28} className="dark:hidden h-6 w-auto" priority />
            <Image src="/white.webp" alt="AI Colab" width={70} height={28} className="hidden dark:block h-6 w-auto" priority />
          </Link>
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to home
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-5 sm:px-8 py-12 sm:py-16">
        <h1 className="text-3xl sm:text-4xl font-bold text-balance">Terms of Use</h1>
        <p className="text-muted-foreground text-sm mt-2">Last updated: {LAST_UPDATED}</p>

        <div className="mt-10 space-y-9 text-[15px] leading-relaxed text-foreground/90">
          {SECTIONS.map((section) => (
            <section key={section.title}>
              <h2 className="text-lg font-semibold text-foreground mb-2">{section.title}</h2>
              {section.body}
            </section>
          ))}
        </div>
      </main>
    </div>
  );
}
