"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Image from "next/image";
import { chatService } from "@/lib/services";
import { MessageList } from "@/components/chat/message-list";
import { Sparkles, AlertCircle } from "lucide-react";

interface Message {
  id: number;
  role: string;
  content: string;
  createdAt: string;
  attachments?: any[];
  modelResponses?: any[];
}

export default function SharedChatPage() {
  const params = useParams();
  const shareId = params.shareId as string;

  const [chat, setChat] = useState<any>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [activeModelTabs, setActiveModelTabs] = useState<Record<number, number>>({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function fetchSharedChat() {
      try {
        const res = await chatService.getShared(shareId);
        const data = res.data.data;
        setChat(data);
        setMessages(data.messages || []);

        const tabs: Record<number, number> = {};
        (data.messages || []).forEach((msg: Message) => {
          if (msg.modelResponses && msg.modelResponses.length > 0) {
            tabs[msg.id] = msg.modelResponses[0].model.id;
          }
        });
        setActiveModelTabs(tabs);
      } catch (err: any) {
        setError(err.response?.data?.message || "Failed to load shared chat");
      } finally {
        setLoading(false);
      }
    }
    fetchSharedChat();
  }, [shareId]);

  if (loading) {
    return (
      <div className="h-dvh flex items-center justify-center bg-background">
        <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (error || !chat) {
    return (
      <div className="h-dvh flex flex-col items-center justify-center bg-background text-center p-6 space-y-4">
        <div className="w-16 h-16 bg-destructive/10 rounded-full flex items-center justify-center mb-2">
          <AlertCircle className="w-8 h-8 text-destructive" />
        </div>
        <h1 className="text-2xl font-bold">Chat Not Found</h1>
        <p className="text-muted-foreground">{error || "This chat link is invalid or has expired."}</p>
      </div>
    );
  }

  return (
    <div className="h-dvh flex flex-col bg-background selection:bg-primary/20">
      {/* Header */}
      <header className="h-14 border-b border-border/50 flex items-center px-6 shrink-0 justify-between bg-background/50 backdrop-blur-md sticky top-0 z-10">
        <div className="flex flex-col">
          <h1 className="font-medium text-sm truncate max-w-[200px] md:max-w-md">{chat.title || "Shared Chat"}</h1>
          <span className="text-xs text-muted-foreground">Shared by {chat.user?.firstName} {chat.user?.lastName}</span>
        </div>
        <div className="flex items-center gap-2">
          <Image src="/black.webp" alt="AI Colab" width={100} height={28} className="dark:hidden h-auto" />
          <Image src="/white.webp" alt="AI Colab" width={100} height={28} className="hidden dark:block h-auto" />
        </div>
      </header>

      {/* Messages */}
      <div className="flex-1 overflow-hidden relative">
        <MessageList 
          messages={messages} 
          activeModelTabs={activeModelTabs} 
          onModelTabChange={(msgId, modelId) => setActiveModelTabs(prev => ({ ...prev, [msgId]: modelId }))}
        />
        
        {/* Faded overlay for read-only indicator */}
        <div className="absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-background to-transparent pointer-events-none" />
      </div>
      
      {/* Read-only Footer */}
      <div className="shrink-0 p-4 border-t border-border/50 bg-muted/30 text-center text-sm text-muted-foreground flex items-center justify-center gap-2">
        <Sparkles className="w-4 h-4 text-primary" />
        This is a read-only shared chat generated by AI Colab.
      </div>
    </div>
  );
}
