"use client";

import {
  useState,
  useEffect,
  useCallback,
  useMemo,
  useRef,
  useSyncExternalStore,
  memo,
  type Dispatch,
  type SetStateAction,
} from "react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Plus, ChevronRight, Edit2, Trash2, MoreHorizontal, Eye, RefreshCw } from "lucide-react";
import { ContextModal } from "@/components/contexts/ContextModal";
import { ContextViewDialog } from "@/components/contexts/ContextViewDialog";
import { ConfirmDialog } from "@/components/dashboard/confirm-dialog";
import { chatService, contextService } from "@/lib/services";
import { toast } from "@/lib/toast";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { SIDEBAR_SECTION_HEADER_ROW, SIDEBAR_SECTION_TITLE } from "@/components/sidebar/sidebar-section-styles";
import type { Chat, FolderItem } from "@/components/sidebar/sidebar-types";
import { getRouteUiSnapshot, subscribeRouteUi } from "@/lib/route-ui-store";

type SidebarContextRow = {
  id: number;
  title?: string;
  memory?: string;
  isAutoGenerated?: boolean;
  isAutoSelected?: boolean;
  origin?: "USER" | "SYSTEM" | "DISTILLED";
};

function ContextSidebarItem({
  ctx,
  isSelected,
  onToggle,
  onView,
  onEdit,
  onDelete,
}: {
  ctx: SidebarContextRow;
  isSelected: boolean;
  onToggle: () => void;
  onView: () => void;
  onEdit: () => void;
  onDelete: () => void;
}) {
  const [menuOpen, setMenuOpen] = useState(false);
  const isSystemContext = Boolean(ctx.isAutoGenerated);
  const isDistilled = ctx.origin === "DISTILLED";
  const content = (
    <div
      className={`group relative flex w-full min-w-0 items-center gap-2 px-3 py-1.5 rounded-lg transition-colors hover:bg-sidebar-accent ${
        isSystemContext ? "cursor-not-allowed opacity-80" : "cursor-pointer"
      }`}
      role="checkbox"
      aria-checked={isSelected}
      aria-disabled={isSystemContext}
      tabIndex={0}
      onClick={() => {
        if (isSystemContext) return;
        onToggle();
      }}
      onKeyDown={(e) => {
        if (isSystemContext) return;
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          onToggle();
        }
      }}
    >
      <input
        type="checkbox"
        checked={isSelected}
        onChange={onToggle}
        disabled={isSystemContext}
        onClick={(e) => {
          e.stopPropagation();
        }}
        className="h-3.5 w-3.5 shrink-0 accent-primary cursor-pointer"
      />
      <span
        className="flex min-w-0 flex-1 items-center gap-1.5 truncate pr-8 text-xs text-foreground"
        title={ctx.title || ctx.memory}
      >
        <span className="truncate">
          {(ctx.title || "Untitled context").length > 30
            ? (ctx.title || "Untitled context").substring(0, 30) + "..."
            : (ctx.title || "Untitled context")}
        </span>
        {isDistilled && (
          <span
            className="shrink-0 rounded bg-muted px-1 py-px text-[9px] font-medium uppercase tracking-wide text-muted-foreground"
            title="Automatically added from a chat in this project"
          >
            Auto
          </span>
        )}
      </span>
      <div className="absolute right-1 top-1/2 flex -translate-y-1/2 items-center">
        <DropdownMenu open={menuOpen} onOpenChange={setMenuOpen}>
          <DropdownMenuTrigger asChild>
            <Button
              variant="ghost"
              className="h-7 w-7 rounded p-0 text-muted-foreground transition-opacity hover:bg-sidebar-accent hover:text-foreground focus:opacity-100 data-[state=open]:opacity-100 md:opacity-0 md:group-hover:opacity-100"
              onClick={(e) => e.stopPropagation()}
            >
              <MoreHorizontal className="w-4 h-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" onClick={(e) => e.stopPropagation()}>
            <DropdownMenuItem className="cursor-pointer gap-2" onClick={onView}>
              <Eye className="h-3.5 w-3.5" />
              View
            </DropdownMenuItem>
            <DropdownMenuItem
              className="cursor-pointer gap-2"
              onClick={(e) => {
                if (isSystemContext) {
                  e.preventDefault();
                  return;
                }
                onEdit();
              }}
              disabled={isSystemContext}
            >
              <Edit2 className="h-3.5 w-3.5" />
              Edit
            </DropdownMenuItem>
            <DropdownMenuItem
              variant="destructive"
              className={`gap-2 ${isSystemContext ? "" : "cursor-pointer"}`}
              disabled={isSystemContext}
              title={
                isSystemContext
                  ? "Cannot delete system generated context"
                  : undefined
              }
              onSelect={(e) => {
                if (isSystemContext) {
                  e.preventDefault();
                  return;
                }
                onDelete();
              }}
            >
              <Trash2 className="h-3.5 w-3.5" />
              Delete
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </div>
  );

  if (isSystemContext) {
    return (
      <TooltipProvider delayDuration={0}>
        <Tooltip>
          <TooltipTrigger asChild>
            {content}
          </TooltipTrigger>
          <TooltipContent side="right">
            System generated context cannot be edited or deleted
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    );
  }

  return content;
}

const ContextsSection = memo(function ContextsSection({
  contextsExpanded,
  setContextsExpanded,
  savingContexts,
  openCreateContextModal,
  loadingContexts,
  allContexts,
  selectedContextIds,
  handleToggleContext,
  openViewContextModal,
  openEditContextModal,
  setContextDeleteTarget,
  activeFolderId,
  syncingProjectMemory,
  onSyncProjectMemory,
}: {
  contextsExpanded: boolean;
  setContextsExpanded: Dispatch<SetStateAction<boolean>>;
  savingContexts: boolean;
  openCreateContextModal: () => void;
  loadingContexts: boolean;
  allContexts: SidebarContextRow[];
  selectedContextIds: number[];
  handleToggleContext: (id: number) => void;
  openViewContextModal: (ctx: SidebarContextRow) => void;
  openEditContextModal: (ctx: SidebarContextRow) => void;
  setContextDeleteTarget: Dispatch<SetStateAction<SidebarContextRow | null>>;
  activeFolderId: number | null;
  syncingProjectMemory: boolean;
  onSyncProjectMemory: () => void;
}) {
  return (
    <>
      <div className={`${SIDEBAR_SECTION_HEADER_ROW}`} data-guide="contexts">
        <button
          type="button"
          className="flex min-w-0 flex-1 items-center gap-2 py-2.5 px-3 text-left"
          onClick={() => setContextsExpanded((p) => !p)}
        >
          <span className={`min-w-0 flex-1 text-left ${SIDEBAR_SECTION_TITLE}`}>Contexts</span>
          {savingContexts && (
            <span className="shrink-0 text-[10px] font-medium normal-case text-muted-foreground/80">
              saving...
            </span>
          )}
        </button>
        {activeFolderId && (
          <div className="flex h-7 w-7 shrink-0 items-center justify-center">
            <Button
              variant="ghost"
              size="icon"
              className="h-7 w-7 cursor-pointer text-muted-foreground hover:text-foreground"
              disabled={syncingProjectMemory}
              onClick={(e) => {
                e.stopPropagation();
                onSyncProjectMemory();
              }}
              title="Sync project memory"
            >
              <RefreshCw className={`h-3.5 w-3.5 ${syncingProjectMemory ? "animate-spin" : ""}`} />
            </Button>
          </div>
        )}
        <div className="flex h-7 w-7 shrink-0 items-center justify-center">
          <Button
            variant="ghost"
            size="icon"
            className="h-7 w-7 cursor-pointer text-muted-foreground hover:text-foreground"
            onClick={(e) => {
              e.stopPropagation();
              openCreateContextModal();
            }}
            title="Add context"
          >
            <Plus className="h-3.5 w-3.5" />
          </Button>
        </div>
        <button
          type="button"
          className="flex h-7 w-7 shrink-0 cursor-pointer items-center justify-center rounded-md text-muted-foreground hover:bg-sidebar-accent/80"
          onClick={() => setContextsExpanded((p) => !p)}
          aria-expanded={contextsExpanded}
          aria-label={contextsExpanded ? "Collapse contexts" : "Expand contexts"}
        >
          <ChevronRight
            className={`h-3 w-3 transition-transform ${contextsExpanded ? "rotate-90" : ""}`}
          />
        </button>
      </div>

      {contextsExpanded && (
        <>
          {loadingContexts ? (
            <div className="px-3 py-2 text-xs text-muted-foreground">
              Loading contexts...
            </div>
          ) : (
            <>
              {allContexts.length === 0 ? (
                <div className="px-3 py-1 text-xs text-muted-foreground/70">
                  No items
                </div>
              ) : (
                allContexts.map((ctx) => {
                  const isSelected = selectedContextIds.includes(ctx.id);
                  return (
                    <ContextSidebarItem
                      key={ctx.id}
                      ctx={ctx}
                      isSelected={isSelected}
                      onToggle={() => handleToggleContext(ctx.id)}
                      onView={() => openViewContextModal(ctx)}
                      onEdit={() => openEditContextModal(ctx)}
                      onDelete={() => {
                        if (ctx?.isAutoGenerated) return;
                        setContextDeleteTarget(ctx);
                      }}
                    />
                  );
                })
              )}
            </>
          )}
        </>
      )}
    </>
  );
});

export function ContextsSectionContainer({
  contextsExpanded,
  setContextsExpanded,
  localFolders,
  pendingNewChatFolderIdKey,
  pendingNewChatContextsKey,
}: {
  contextsExpanded: boolean;
  setContextsExpanded: Dispatch<SetStateAction<boolean>>;
  localFolders: FolderItem[];
  pendingNewChatFolderIdKey: string;
  pendingNewChatContextsKey: string;
}) {
  const activeChatId = useSyncExternalStore(
    subscribeRouteUi,
    () => getRouteUiSnapshot().activeChatId,
    () => null,
  );
  const [sidebarContexts, setSidebarContexts] = useState<{
    globalContexts: SidebarContextRow[];
    folderContexts: SidebarContextRow[];
    customContexts: SidebarContextRow[];
  }>({ globalContexts: [], folderContexts: [], customContexts: [] });
  const [selectedContextIds, setSelectedContextIds] = useState<number[]>([]);
  const [activeFolderId, setActiveFolderId] = useState<number | null>(null);
  const [loadingContexts, setLoadingContexts] = useState(false);
  const [savingContexts, setSavingContexts] = useState(false);
  const [syncingProjectMemory, setSyncingProjectMemory] = useState(false);
  const [contextModalOpen, setContextModalOpen] = useState(false);
  const [contextModalMode, setContextModalMode] = useState<"create" | "edit">("create");
  const [activeContext, setActiveContext] = useState<unknown>(null);
  const [contextDetailView, setContextDetailView] = useState<SidebarContextRow | null>(null);
  const [savingContextModal, setSavingContextModal] = useState(false);
  const [contextDeleteTarget, setContextDeleteTarget] = useState<SidebarContextRow | null>(null);
  const [deletingContext, setDeletingContext] = useState(false);
  const contextFetchInFlightRef = useRef(false);
  const lastContextFetchKeyRef = useRef<string>("");
  const lastSidebarFolderKeyRef = useRef<string | null>(null);
  const sidebarAvailablePayloadRef = useRef<{
    globalContexts: SidebarContextRow[];
    folderContexts: SidebarContextRow[];
    customContexts: SidebarContextRow[];
  } | null>(null);
  const chatsRef = useRef<Chat[]>([]);

  const getFolderDisplayName = useCallback(
    (folderId: number) => localFolders.find((f) => f.id === folderId)?.name || "Unknown Folder",
    [localFolders],
  );

  const refreshSidebarContexts = useCallback(
    async (chatId?: number | null, folderIdHint?: number | null, force = false) => {
      let folderId = folderIdHint ?? null;
      if (chatId && folderId === null) {
        const activeChat =
          chatsRef.current.find((chat) => chat.id === chatId) ||
          (await chatService.getById(chatId)).data.data;
        folderId = activeChat?.folderId ?? null;
      }
      setActiveFolderId(chatId ? folderId : null);

      const folderKey = `${folderId ?? "none"}`;
      const requestKey = `${chatId ?? "new"}:${folderKey}`;
      const cached = sidebarAvailablePayloadRef.current;
      const canReuseAvailable =
        !force && lastSidebarFolderKeyRef.current === folderKey && cached != null;

      if (canReuseAvailable) {
        if (!force && lastContextFetchKeyRef.current === requestKey) return;
        try {
          if (chatId) {
            const selectedRes = await chatService.getContexts(chatId);
            setSelectedContextIds(selectedRes.data?.data?.contextIds || []);
          } else {
            const payload = cached;
            const defaultGlobalIds = (payload.globalContexts || [])
              .filter((ctx: SidebarContextRow) => ctx.isAutoSelected)
              .map((ctx: SidebarContextRow) => ctx.id);
            const defaultFolderIds = folderId
              ? (payload.folderContexts || []).map((ctx: SidebarContextRow) => ctx.id)
              : [];
            const defaultContextIds = [...defaultGlobalIds, ...defaultFolderIds];
            const stored = localStorage.getItem(pendingNewChatContextsKey);
            if (stored) {
              try {
                const parsed = JSON.parse(stored);
                setSelectedContextIds(
                  Array.isArray(parsed)
                    ? parsed.map((id: unknown) => Number(id)).filter((id) => !Number.isNaN(id))
                    : defaultContextIds,
                );
              } catch {
                setSelectedContextIds(defaultContextIds);
              }
            } else {
              setSelectedContextIds(defaultContextIds);
            }
          }
          lastContextFetchKeyRef.current = requestKey;
        } catch {
          setSelectedContextIds([]);
        }
        return;
      }

      if (!force && (contextFetchInFlightRef.current || lastContextFetchKeyRef.current === requestKey)) {
        return;
      }

      contextFetchInFlightRef.current = true;
      lastContextFetchKeyRef.current = requestKey;
      setLoadingContexts(true);
      try {
        const availableRes = await contextService.getSidebar(
          folderId ? { folderId: String(folderId) } : undefined,
        );
        const payload = availableRes.data?.data || {
          globalContexts: [],
          folderContexts: [],
          customContexts: [],
        };
        lastSidebarFolderKeyRef.current = folderKey;
        sidebarAvailablePayloadRef.current = payload;
        setSidebarContexts(payload);

        if (chatId) {
          const selectedRes = await chatService.getContexts(chatId);
          setSelectedContextIds(selectedRes.data?.data?.contextIds || []);
        } else {
          const defaultGlobalIds = (payload.globalContexts || [])
            .filter((ctx: SidebarContextRow) => ctx.isAutoSelected)
            .map((ctx: SidebarContextRow) => ctx.id);
          const defaultFolderIds = folderId
            ? (payload.folderContexts || []).map((ctx: SidebarContextRow) => ctx.id)
            : [];
          const defaultContextIds = [...defaultGlobalIds, ...defaultFolderIds];
          const stored = localStorage.getItem(pendingNewChatContextsKey);
          if (stored) {
            try {
              const parsed = JSON.parse(stored);
              setSelectedContextIds(
                Array.isArray(parsed)
                  ? parsed.map((id: unknown) => Number(id)).filter((id) => !Number.isNaN(id))
                  : defaultContextIds,
              );
            } catch {
              setSelectedContextIds(defaultContextIds);
            }
          } else {
            setSelectedContextIds(defaultContextIds);
          }
        }
      } catch {
        lastSidebarFolderKeyRef.current = null;
        sidebarAvailablePayloadRef.current = null;
        setSidebarContexts({ globalContexts: [], folderContexts: [], customContexts: [] });
        setSelectedContextIds([]);
        setActiveFolderId(null);
      } finally {
        contextFetchInFlightRef.current = false;
        setLoadingContexts(false);
      }
    },
    [pendingNewChatContextsKey],
  );

  const getNewChatFolderIdHint = useCallback(() => {
    try {
      const raw = localStorage.getItem(pendingNewChatFolderIdKey);
      const parsed = raw ? Number(raw) : NaN;
      if (!Number.isNaN(parsed)) return parsed;
    } catch {
      // ignore localStorage issues
    }
    try {
      const params = new URLSearchParams(window.location.search);
      const raw = params.get("folderId");
      if (!raw) return null;
      const parsed = Number(raw);
      return Number.isNaN(parsed) ? null : parsed;
    } catch {
      return null;
    }
  }, [pendingNewChatFolderIdKey]);

  useEffect(() => {
    const folderIdHint = activeChatId ? undefined : getNewChatFolderIdHint();
    void refreshSidebarContexts(activeChatId, folderIdHint);
  }, [activeChatId, getNewChatFolderIdHint, refreshSidebarContexts]);

  useEffect(() => {
    const handler = (evt: Event) => {
      if (getRouteUiSnapshot().activeChatId) return;
      const customEvt = evt as CustomEvent<{ folderId?: number | null }>;
      const folderIdFromEvent =
        customEvt.detail && "folderId" in customEvt.detail
          ? customEvt.detail.folderId ?? null
          : undefined;
      const folderIdHint =
        folderIdFromEvent !== undefined ? folderIdFromEvent : getNewChatFolderIdHint();
      void refreshSidebarContexts(null, folderIdHint, true);
    };
    window.addEventListener("pending-new-chat-folder-updated", handler as EventListener);
    return () =>
      window.removeEventListener("pending-new-chat-folder-updated", handler as EventListener);
  }, [getNewChatFolderIdHint, refreshSidebarContexts]);

  useEffect(() => {
    const handler = () => {
      const activeId = getRouteUiSnapshot().activeChatId;
      void refreshSidebarContexts(activeId, activeId ? undefined : getNewChatFolderIdHint(), true);
    };
    window.addEventListener("contexts-updated", handler);
    return () => window.removeEventListener("contexts-updated", handler);
  }, [getNewChatFolderIdHint, refreshSidebarContexts]);

  const handleToggleContext = useCallback(
    async (contextId: number) => {
      if (savingContexts) return;
      const next = selectedContextIds.includes(contextId)
        ? selectedContextIds.filter((id) => id !== contextId)
        : [...selectedContextIds, contextId];

      setSelectedContextIds(next);
      const chatId = getRouteUiSnapshot().activeChatId;
      if (!chatId) {
        localStorage.setItem(pendingNewChatContextsKey, JSON.stringify(next));
        return;
      }
      setSavingContexts(true);
      try {
        await chatService.replaceContexts(chatId, next);
      } catch {
        toast.error("Failed to update chat contexts");
        await refreshSidebarContexts(getRouteUiSnapshot().activeChatId);
      } finally {
        setSavingContexts(false);
      }
    },
    [pendingNewChatContextsKey, refreshSidebarContexts, savingContexts, selectedContextIds],
  );

  // Existing chats only get a folder's contexts as a one-time snapshot at
  // creation — new project memory added afterward (manually, or by the
  // distillation worker) doesn't automatically reach them. This pulls the
  // folder's current context list and attaches anything the chat is
  // missing, without removing anything the user has deliberately unchecked.
  const handleSyncProjectMemory = useCallback(
    async () => {
      const chatId = getRouteUiSnapshot().activeChatId;
      if (!chatId || !activeFolderId || syncingProjectMemory) return;

      setSyncingProjectMemory(true);
      try {
        const availableRes = await contextService.getSidebar({
          folderId: String(activeFolderId),
        });
        const payload = availableRes.data?.data || {
          globalContexts: [],
          folderContexts: [],
          customContexts: [],
        };
        sidebarAvailablePayloadRef.current = payload;
        setSidebarContexts(payload);

        const folderContextIds = (payload.folderContexts || []).map(
          (ctx: SidebarContextRow) => ctx.id,
        );
        const mergedIds = Array.from(new Set([...selectedContextIds, ...folderContextIds]));

        if (mergedIds.length === selectedContextIds.length) {
          toast.success("Project memory already up to date");
          return;
        }

        setSelectedContextIds(mergedIds);
        await chatService.replaceContexts(chatId, mergedIds);
        toast.success("Project memory synced");
      } catch {
        toast.error("Failed to sync project memory");
      } finally {
        setSyncingProjectMemory(false);
      }
    },
    [activeFolderId, selectedContextIds, syncingProjectMemory],
  );

  const allContexts = useMemo(() => {
    const seen = new Set<number>();
    const merged = [
      ...sidebarContexts.globalContexts,
      ...sidebarContexts.folderContexts,
      ...sidebarContexts.customContexts,
    ].filter((ctx: SidebarContextRow) => {
      if (!ctx?.id || seen.has(ctx.id)) return false;
      seen.add(ctx.id);
      return true;
    });
    return merged.sort((a: SidebarContextRow, b: SidebarContextRow) => {
      const aSelected = selectedContextIds.includes(a.id) ? 1 : 0;
      const bSelected = selectedContextIds.includes(b.id) ? 1 : 0;
      if (aSelected !== bSelected) return bSelected - aSelected;
      return String(a.title || "").localeCompare(String(b.title || ""));
    });
  }, [sidebarContexts, selectedContextIds]);

  const openCreateContextModal = useCallback(() => {
    setActiveContext(null);
    setContextModalMode("create");
    setContextModalOpen(true);
  }, []);
  const openViewContextModal = useCallback((context: SidebarContextRow) => setContextDetailView(context), []);
  const openEditContextModal = useCallback((context: SidebarContextRow) => {
    setActiveContext(context);
    setContextModalMode("edit");
    setContextModalOpen(true);
  }, []);

  const handleSaveContext = async (data: {
    type?: string;
    isAutoSelected?: boolean;
    [key: string]: unknown;
  }) => {
    setSavingContextModal(true);
    try {
      const editing = activeContext as { id?: number } | null;
      if (contextModalMode === "edit" && editing?.id) {
        await contextService.update(editing.id, {
          ...data,
          isAutoSelected: data.type === "GLOBAL" ? data.isAutoSelected : false,
        });
        toast.success("Context updated");
      } else {
        const created = await contextService.create({
          ...data,
          isAutoSelected: data.type === "GLOBAL" ? data.isAutoSelected : false,
        });
        const createdContextId = created.data?.data?.id;
        const chatIdAfterCreate = getRouteUiSnapshot().activeChatId;
        if (chatIdAfterCreate && createdContextId) {
          const nextIds = Array.from(new Set([...selectedContextIds, createdContextId]));
          setSelectedContextIds(nextIds);
          await chatService.replaceContexts(chatIdAfterCreate, nextIds);
        }
        toast.success("Context created");
      }
      setContextModalOpen(false);
      await refreshSidebarContexts(getRouteUiSnapshot().activeChatId, undefined, true);
    } catch {
      toast.error("Failed to save context");
    } finally {
      setSavingContextModal(false);
    }
  };

  const handleDeleteContext = async () => {
    if (!contextDeleteTarget?.id || contextDeleteTarget.isAutoGenerated) {
      if (contextDeleteTarget?.isAutoGenerated) {
        toast.error("This is system generated context, cannot be deleted");
        setContextDeleteTarget(null);
      }
      return;
    }
    setDeletingContext(true);
    try {
      await contextService.delete(contextDeleteTarget.id);
      toast.success("Context deleted");
      setContextDeleteTarget(null);
      await refreshSidebarContexts(getRouteUiSnapshot().activeChatId, undefined, true);
    } catch {
      toast.error("Failed to delete context");
    } finally {
      setDeletingContext(false);
    }
  };

  return (
    <>
      <ContextsSection
        contextsExpanded={contextsExpanded}
        setContextsExpanded={setContextsExpanded}
        savingContexts={savingContexts}
        openCreateContextModal={openCreateContextModal}
        loadingContexts={loadingContexts}
        allContexts={allContexts}
        selectedContextIds={selectedContextIds}
        handleToggleContext={handleToggleContext}
        openViewContextModal={openViewContextModal}
        openEditContextModal={openEditContextModal}
        setContextDeleteTarget={setContextDeleteTarget}
        activeFolderId={activeFolderId}
        syncingProjectMemory={syncingProjectMemory}
        onSyncProjectMemory={handleSyncProjectMemory}
      />

      <ContextModal
        isOpen={contextModalOpen}
        onClose={() => setContextModalOpen(false)}
        onSave={handleSaveContext}
        initialData={activeContext}
        folders={localFolders}
        isSaving={savingContextModal}
        mode={contextModalMode}
      />

      <ContextViewDialog
        open={!!contextDetailView}
        onOpenChange={(open) => !open && setContextDetailView(null)}
        context={contextDetailView}
        getFolderName={getFolderDisplayName}
      />

      <ConfirmDialog
        open={!!contextDeleteTarget}
        onOpenChange={(open) => {
          if (!open && !deletingContext) setContextDeleteTarget(null);
        }}
        title="Delete Context"
        description={`Are you sure you want to delete "${contextDeleteTarget?.title || "this context"}"? This action cannot be undone.`}
        onConfirm={handleDeleteContext}
        loading={deletingContext}
      />
    </>
  );
}
