import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Eye, Edit2, Trash2 } from "lucide-react";

interface ContextTableProps {
  contexts: any[];
  folders: any[];
  onView: (ctx: any) => void;
  onEdit: (ctx: any) => void;
  onDelete: (ctx: any) => void;
}

export function ContextTable({ contexts, folders, onView, onEdit, onDelete }: ContextTableProps) {
  const getFolderName = (folderId: number) => {
    if (!Array.isArray(folders)) return "Unknown Folder";
    return folders.find((f) => f.id === folderId)?.name || "Unknown Folder";
  };

  if (!contexts || contexts.length === 0) {
    return (
      <div className="py-8 text-center bg-muted/20 border border-border/50 rounded-lg">
        <p className="text-sm text-muted-foreground">No custom contexts found.</p>
      </div>
    );
  }

  return (
    <div className="rounded-md border bg-card">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Title</TableHead>
            <TableHead>Content Info</TableHead>
            <TableHead>Type</TableHead>
            <TableHead>Auto-Selected</TableHead>
            <TableHead>Created</TableHead>
            <TableHead className="text-right">Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {contexts.map((ctx) => (
            <TableRow key={ctx.id}>
              <TableCell className="font-medium max-w-[150px] truncate" title={ctx.title}>
                {ctx.title}
              </TableCell>
              <TableCell className="max-w-[200px] truncate text-muted-foreground text-xs" title={ctx.memory}>
                {ctx.memory}
              </TableCell>
              <TableCell>
                <div className="flex flex-col gap-1 items-start">
                  <Badge variant={ctx.type === "GLOBAL" ? "default" : ctx.type === "FOLDER" ? "secondary" : "outline"}>
                    {ctx.type}
                  </Badge>
                  {ctx.type === "FOLDER" && ctx.folderId && (
                    <span className="text-[10px] text-muted-foreground ml-1">
                      in {getFolderName(ctx.folderId)}
                    </span>
                  )}
                </div>
              </TableCell>
              <TableCell>
                <Badge variant={ctx.isAutoSelected ? "default" : "secondary"} className="text-[10px] uppercase">
                  {ctx.isAutoSelected ? "Yes" : "No"}
                </Badge>
              </TableCell>
              <TableCell className="text-xs whitespace-nowrap">
                {new Date(ctx.createdAt).toLocaleDateString("en-US", {
                  month: "short",
                  day: "numeric",
                  year: "numeric",
                })}
              </TableCell>
              <TableCell className="text-right whitespace-nowrap">
                <div className="flex justify-end gap-1">
                  <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:text-foreground" onClick={() => onView(ctx)}>
                    <Eye className="w-4 h-4" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-8 w-8 text-muted-foreground hover:text-blue-500"
                    disabled={ctx.isAutoGenerated}
                    onClick={() => {
                      if (ctx.isAutoGenerated) return;
                      onEdit(ctx);
                    }}
                    title={ctx.isAutoGenerated ? "Cannot edit system generated context" : "Edit"}
                  >
                    <Edit2 className="w-4 h-4" />
                  </Button>
                  <Button 
                    variant="ghost" 
                    size="icon" 
                    className="h-8 w-8 text-muted-foreground hover:text-destructive hover:bg-destructive/10"
                    disabled={ctx.isAutoGenerated}
                    onClick={() => onDelete(ctx)}
                    title={ctx.isAutoGenerated ? "Cannot delete system generated context" : "Delete"}
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
