"use client";

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";

export interface ContextViewModel {
  id?: number;
  title?: string;
  memory?: string;
  type?: string;
  folderId?: number | null;
  isAutoSelected?: boolean;
  isAutoGenerated?: boolean;
  origin?: "USER" | "SYSTEM" | "DISTILLED";
  createdAt?: string;
}

interface ContextViewDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  context: ContextViewModel | null;
  /** Folder id → display name (e.g. from folder list) */
  getFolderName: (folderId: number) => string;
}

export function ContextViewDialog({
  open,
  onOpenChange,
  context,
  getFolderName,
}: ContextViewDialogProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Context Details</DialogTitle>
        </DialogHeader>
        {context && (
          <div className="space-y-3 text-sm">
            <div className="flex items-center gap-2">
              <span className="text-muted-foreground">Title: </span>
              <span className="font-medium">{context.title}</span>
              {context.origin === "DISTILLED" && (
                <Badge
                  variant="outline"
                  className="text-[9px] uppercase tracking-wide text-muted-foreground"
                  title="Automatically added from a chat in this project"
                >
                  Auto
                </Badge>
              )}
            </div>
            <div className="grid grid-cols-2 gap-2">
              <div>
                <span className="text-muted-foreground">Type: </span>
                <Badge
                  variant={
                    context.type === "GLOBAL"
                      ? "default"
                      : context.type === "FOLDER"
                        ? "secondary"
                        : "outline"
                  }
                >
                  {context.type === "CUSTOM" ? "CHAT" : context.type}
                </Badge>
              </div>
              <div>
                <span className="text-muted-foreground">Auto-Selected: </span>
                <Badge
                  variant={context.isAutoSelected ? "default" : "secondary"}
                  className="text-[10px] uppercase"
                >
                  {context.type === "GLOBAL"
                    ? context.isAutoSelected
                      ? "Yes"
                      : "No"
                    : "N/A"}
                </Badge>
              </div>
            </div>
            {context.type === "FOLDER" && context.folderId && (
              <div>
                <span className="text-muted-foreground">Folder: </span>
                <span className="font-medium">{getFolderName(context.folderId)}</span>
              </div>
            )}
            <div>
              <p className="text-muted-foreground mb-1">Memory Content:</p>
              <p className="bg-muted/40 rounded-lg p-3 text-sm leading-relaxed whitespace-pre-wrap">
                {context.memory}
              </p>
            </div>
            {context.origin === "DISTILLED" && (
              <p className="text-xs text-muted-foreground/80">
                Automatically extracted from a chat in this project. Editing it will make it a
                regular project memory that won&apos;t be auto-updated further.
              </p>
            )}
            {context.createdAt && (
              <div className="text-xs text-muted-foreground">
                Created: {new Date(context.createdAt).toLocaleString()}
              </div>
            )}
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
