import { useState, useEffect } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Loader2 } from "lucide-react";

const MAX_CHARS = 500;

interface Folder {
  id: number;
  name: string;
}

interface ContextModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (data: any) => Promise<void>;
  initialData?: any;
  folders: Folder[];
  isSaving: boolean;
  mode: "create" | "edit" | "view";
}

export function ContextModal({
  isOpen,
  onClose,
  onSave,
  initialData,
  folders,
  isSaving,
  mode,
}: ContextModalProps) {
  const isAutoGenerated = Boolean(initialData?.isAutoGenerated);
  const isLockedEdit = mode === "edit" && isAutoGenerated;
  const [title, setTitle] = useState("");
  const [memory, setMemory] = useState("");
  const [type, setType] = useState<"GLOBAL" | "FOLDER" | "CUSTOM">("GLOBAL");
  const [folderId, setFolderId] = useState<string>("none");
  const [isAutoSelected, setIsAutoSelected] = useState(true);

  useEffect(() => {
    if (isOpen) {
      if (initialData) {
        setTitle(initialData.title || "");
        setMemory(initialData.memory || "");
        setType(initialData.type || "GLOBAL");
        setFolderId(initialData.folderId ? String(initialData.folderId) : "none");
        setIsAutoSelected(initialData.isAutoSelected ?? true);
      } else {
        setTitle("");
        setMemory("");
        setType("GLOBAL");
        setFolderId("none");
        setIsAutoSelected(true);
      }
    }
  }, [isOpen, initialData]);

  useEffect(() => {
    if (type === "GLOBAL") {
      setIsAutoSelected(true);
    }
  }, [type]);

  const handleSave = () => {
    if (isLockedEdit) return; // System-generated contexts can't be edited.
    if (!title.trim() || !memory.trim()) return;

    onSave({
      title: title.trim(),
      memory: memory.trim(),
      type,
      folderId: type === "FOLDER" && folderId !== "none" ? Number(folderId) : null,
      isAutoSelected: type === "GLOBAL" ? true : isAutoSelected,
    });
  };

  const isViewOnly = mode === "view" || isLockedEdit;
  const charsLeft = MAX_CHARS - memory.length;

  // Explicit array check for safety
  const folderList = Array.isArray(folders) ? folders : [];

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !isSaving && !open && onClose()}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>
            {mode === "create" ? "Create Context" : mode === "edit" ? "Edit Context" : "View Context"}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <label htmlFor="title" className="text-sm font-medium">Title</label>
            <Input
              id="title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. My Profession"
              disabled={isViewOnly || isSaving}
            />
          </div>

          <div className="space-y-2">
            <label htmlFor="type" className="text-sm font-medium">Context Scope</label>
            <Select
              value={type}
              onValueChange={(val: any) => setType(val)}
              disabled={isViewOnly || isSaving || (mode === "edit" && initialData?.isAutoGenerated)}
            >
              <SelectTrigger id="type">
                <SelectValue placeholder="Select scope" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="GLOBAL">Global (Active across all chats)</SelectItem>
                <SelectItem value="FOLDER">Folder Specific (Active in one folder)</SelectItem>
                <SelectItem value="CUSTOM">Chat Specific (Manually added to chats)</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {type === "FOLDER" && (
            <div className="space-y-2 animate-in fade-in zoom-in-95 duration-200">
              <label htmlFor="folder" className="text-sm font-medium">Apply to Folder</label>
              <Select
                value={folderId}
                onValueChange={setFolderId}
                disabled={isViewOnly || isSaving}
              >
                <SelectTrigger id="folder">
                  <SelectValue placeholder="Select a folder" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">-- Select Folder --</SelectItem>
                  {folderList.map((f) => (
                    <SelectItem key={f.id} value={String(f.id)}>
                      {f.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}

          {type === "GLOBAL" && (
            <div className="flex items-center justify-between gap-4 py-2">
              <div className="space-y-0.5">
                <label htmlFor="auto-select" className="text-sm font-medium">Auto-apply to new chats</label>
                <p className="text-xs text-muted-foreground">
                  Automatically apply this global context for newly created chats.
                </p>
              </div>
              <Switch
                id="auto-select"
                checked={isAutoSelected}
                onCheckedChange={setIsAutoSelected}
                disabled={isViewOnly || isSaving}
              />
            </div>
          )}

          <div className="space-y-2">
            <div className="flex justify-between items-center">
              <label htmlFor="memory" className="text-sm font-medium">Memory Content</label>
              {!isViewOnly && (
                <span className={`text-xs tabular-nums ${
                    memory.length > MAX_CHARS - 20 ? (memory.length >= MAX_CHARS ? "text-destructive font-medium" : "text-amber-500") : "text-muted-foreground/60"
                  }`}
                >
                  {charsLeft}
                </span>
              )}
            </div>
            <Textarea
              id="memory"
              value={memory}
              onChange={(e) => setMemory(e.target.value.substring(0, MAX_CHARS))}
              placeholder="e.g. I am a software engineer focused on front-end React development."
              className="min-h-[120px] resize-none"
              disabled={isViewOnly || isSaving}
            />
          </div>
        </div>

        <DialogFooter>
          {!isViewOnly && (
            <>
              <Button variant="outline" onClick={onClose} disabled={isSaving}>
                Cancel
              </Button>
              <Button
                onClick={handleSave}
                disabled={!title.trim() || !memory.trim() || (type === "FOLDER" && (folderId === "none" || !folderId)) || isSaving}
              >
                {isSaving ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Saving...
                  </>
                ) : (
                  "Save Context"
                )}
              </Button>
            </>
          )}
          {isViewOnly && (
            <Button onClick={onClose}>Close</Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
